# config.yml
github:
  repo: "BlakeOO2/UltimateStaff"
  branch: "main"
auto-update: true

chat:
  staff:
    default-format: "&6[SC] &7[%server%] %prefix%%name%&7: &f%message%"
    group-formats:
      owner: "&6[SC] &4OWNER &7[%server%] %name%&7: &f%message%"
      admin: "&6[SC] &cAdmin &7[%server%] %name%&7: &f%message%"
      head-mod: "&6[SC] &4HMod &7[%server%] %name%&7: &f%message%"
      mod: "&6[SC] &2Mod &7[%server%] %name%&7: &f%message%"
      trial-mod: "&6[SC] &aTMod &7[%server%] %name%&7: &f%message%"
      helper: "&6[SC] &eHelper &7[%server%] %name%&7: &f%message%"
    sound:
      enabled: true
      type: "ENTITY_EXPERIENCE_ORB_PICKUP"
      volume: 1.0
      pitch: 1.0

  admin:
    default-format: "&c[AC] &7[%server%] %prefix%%name%&7: &f%message%"
    group-formats:
      owner: "&c[AC] &4OWNER &7[%server%] %name%&7: &f%message%"
      admin: "&c[AC] &cAdmin &7[%server%] %name%&7: &f%message%"
      head-mod: "&c[AC] &4HMod &7[%server%] %name%&7: &f%message%"
    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1.0
      pitch: 2.0

# Store player preferences
data:
  staff-chat-sound-disabled: []
  admin-chat-sound-disabled: []




discord:
  enabled: true
  bot-token: "AddTokenHere"
  channels:
    staff-chat: "1372452537680269372"  # Discord channel ID for staff chat
    admin-chat: "1367550043065815142"  # Discord channel ID for admin chat
  format:
    discord-to-minecraft: "&9[Discord] &b%username%&f: %message%"
    minecraft-to-discord: "**[MC]** %username%: %message%"


mining-alerts:
  global:
    default-enabled: true
    staff-preferences:
      alert-radius: 100
      format-options:
        show-coordinates: true
        show-world: true
    colors:
      normal: "&e"
      vein: "&a"
      suspicious: "&c"

  diamond_ore:
    enabled: true
    message: "&6[Mining] &e%player% found Diamond Ore at %x%, %y%, %z%"
    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1.0
      pitch: 1.0

  deepslate_diamond_ore:
    enabled: true
    message: "&6[Mining] &e%player% found Deepslate Diamond Ore at %x%, %y%, %z%"
    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1.0
      pitch: 1.0

  ancient_debris:
    enabled: true
    message: "&6[Mining] &e%player% found Ancient Debris at %x%, %y%, %z%"
    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_PLING"
      volume: 1.0
      pitch: 1.0

punishments:
  respect_and_chat:
    name: "Respect & Chat"
    icon: BOOK
    slot: 10
    violations:
      harassment:
        name: "Harassment / Disrespect"
        item:
          material: RED_WOOL
          name: "&c&lHarassment / Disrespect"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "Warning"
            command: "warn %player% Harassment/Disrespect"
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Harassment/Disrespect"
          - name: "Permanent Ban"
            command: "ban %player% Harassment/Disrespect"

      chat_abuse:
        name: "Chat Abuse / Spam"
        item:
          material: ORANGE_WOOL
          name: "&c&lChat Abuse / Spam"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 1h Mute"
            - "&7→ 24h Mute"
            - "&7→ Permanent Mute"
        actions:
          - name: "Warning"
            command: "warn %player% Chat Abuse/Spam"
          - name: "1h Mute"
            duration: "1h"
            command: "tempmute %player% %duration% Chat Abuse/Spam"
          - name: "24h Mute"
            duration: "24h"
            command: "tempmute %player% %duration% Chat Abuse/Spam"
          - name: "Permanent Mute"
            command: "mute %player% Chat Abuse/Spam"

      threats:
        name: "Threats"
        item:
          material: BLACK_WOOL
          name: "&4&lThreats"
          lore:
            - "&7Immediate action:"
            - "&7→ Permanent Ban"
            - "&7→ Blacklist"
        actions:
          - name: "Permanent Ban"
            command: "ban %player% Threats (Doxing/DDoS/Malicious Links)"

      impersonation:
        name: "Impersonation"
        item:
          material: PLAYER_HEAD
          name: "&c&lImpersonation"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "Warning"
            command: "warn %player% Impersonation of Staff/Players"
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Impersonation"
          - name: "Permanent Ban"
            command: "ban %player% Impersonation"

  gameplay:
    name: "Gameplay Violations"
    icon: DIAMOND_SWORD
    slot: 12
    violations:
      unfair_advantage:
        name: "Unfair Advantage"
        item:
          material: COMMAND_BLOCK
          name: "&c&lUnfair Advantage"
          lore:
            - "&7Progression:"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Using unfair mods/macros/scripts"
          - name: "Permanent Ban"
            command: "ban %player% Using unfair mods/macros/scripts"

      cheating:
        name: "Cheating"
        item:
          material: BARRIER
          name: "&4&lCheating"
          lore:
            - "&7Immediate action:"
            - "&7→ Permanent Ban"
        actions:
          - name: "Permanent Ban"
            command: "ban %player% Cheating (X-Ray/Freecam/Hacks)"

      pvp_violations:
        name: "Non-Consensual PvP"
        item:
          material: IRON_SWORD
          name: "&c&lNon-Consensual PvP"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "Warning"
            command: "warn %player% Non-Consensual PvP"
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Non-Consensual PvP"
          - name: "Permanent Ban"
            command: "ban %player% Repeated Non-Consensual PvP"

  building:
    name: "Building Violations"
    icon: BRICKS
    slot: 14
    violations:
      griefing:
        name: "Griefing"
        item:
          material: TNT
          name: "&c&lGriefing"
          lore:
            - "&7Progression:"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Griefing"
          - name: "Permanent Ban"
            command: "ban %player% Griefing"

      building_violations:
        name: "Building Violations"
        item:
          material: WOODEN_AXE
          name: "&c&lBuilding Violations"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 24h Ban"
        actions:
          - name: "Warning"
            command: "warn %player% Building violation"
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Repeated building violations"

  economy:
    name: "Economy Violations"
    icon: GOLD_INGOT
    slot: 16
    violations:
      scamming:
        name: "Scamming"
        item:
          material: CHEST
          name: "&c&lScamming"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "Warning"
            command: "warn %player% Scamming"
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Scamming"
          - name: "Permanent Ban"
            command: "ban %player% Repeated scamming"

      irl_trading:
        name: "IRL Trading"
        item:
          material: EMERALD
          name: "&4&lIRL Trading"
          lore:
            - "&7Immediate action:"
            - "&7→ Permanent Ban"
        actions:
          - name: "Permanent Ban"
            command: "ban %player% IRL Trading"

  inappropriate:
    name: "Inappropriate Content"
    icon: WRITABLE_BOOK
    slot: 28
    violations:
      inappropriate_content:
        name: "Inappropriate Content"
        item:
          material: PAPER
          name: "&c&lInappropriate Content"
          lore:
            - "&7Progression:"
            - "&7→ Warning"
            - "&7→ 24h Ban"
            - "&7→ Permanent Ban"
        actions:
          - name: "Warning"
            command: "warn %player% Inappropriate content"
          - name: "24h Ban"
            duration: "24h"
            command: "tempban %player% %duration% Inappropriate content"
          - name: "Permanent Ban"
            command: "ban %player% Repeated inappropriate content"
