name: UltimateStaff
version: '${project.version}'
main: com.smokypeaks.Main
api-version: '1.21'
softdepends: [LuckPerms]
authors: [Hydrantz]  # Note the square brackets to make it a list
description: Ultimate staff management plugin
libraries:
  - com.google.code.gson:gson:2.10.1
commands:
  ultimatestaff:
    description: Main command for UltimateStaff plugin
    usage: /ultimatestaff <subcommand>
    aliases: [us, ustaff]
    permission: ultimatestaff.staff.use
  ultimatestaffupdate:
    description: Check for plugin updates
    usage: /ultimatestaffupdate
    permission: ultimatestaff.admin.updates
  staffmode:
    description: Toggle staff mode
    usage: /staffmode
    aliases: [ sm, staff ]
    permission: ultimatestaff.staff.mode
  endersee:
    description: View a player's enderchest
    usage: /endersee <player>
    aliases: [ echest, ec ]
    permission: ultimatestaff.staff.endersee
  invsee:
    description: View a player's inventory
    usage: /invsee <player> [enderchest]
    aliases: [ inv ]
    permission: ultimatestaff.staff.invsee
  stp:
    description: Staff teleport commands
    usage: /stp <player|random|back|pos> [args]
    aliases: [ stafftp ]
    permission: ultimatestaff.staff.teleport
  miningalerts:
    description: Toggle mining alerts
    usage: /miningalerts
    aliases: [ ma, minealert ]
    permission: ultimatestaff.staff.alerts.mining
  miningconfig:
    description: Configure mining alerts
    usage: /miningconfig <toggle|message|sound> <material> [args]
    permission: ultimatestaff.admin.alerts.config
  restart:
    description: Schedule a server restart
    usage: /restart <time> [reason]
    aliases: [ serverrestart, usrestart ]
    permission: ultimatestaff.admin.restart
  reloadpunishments:
    description: Reload punishment configurations
    permission: ultimatestaff.admin.reload
  miningdebug:
    description: Debug mining alert settings
    permission: ultimatestaff.admin.debug
  discordreload:
    description: Reload Discord integration
    usage: /discordreload
    permission: ultimatestaff.admin.discord

  clearchat:
    description: Clear the chat for all players or specific players
    usage: /clearchat [self|player <name>|all]
    aliases: [ cc ]
    permission: ultimatestaff.staff.clearchat

  automod:
    description: Configure and control the AutoMod system
    aliases: [am]
    permission: ultimatestaff.admin.automod
  punish:
    description: Open the punishment GUI for a player
    aliases: [p]
    permission: ultimatestaff.staff.punish
  deathlocation:
    description: View a player's death location
    aliases: [dloc, deathloc]
    permission: ultimatestaff.staff.deathlocation
  restoredeathitems:
    description: Restore a player's death items
    aliases: [rdi, deathitems]
    permission: ultimatestaff.admin.restoredeathitems
  chatfilter:
    description: Manage the chat filter
    aliases: [cf]
    permission: ultimatestaff.admin.chatfilter
  punishdebug:
    description: Debug the punishment system
    permission: ultimatestaff.admin.punishdebug
  xray:
    description: Manage and monitor the AntiXray system
    aliases: [antixray]
    permission: ultimatestaff.staff.xray_commands
  xraylearn:
    description: Configure and control the AntiXray learning system
    aliases: [xlearning, xlearner]
    permission: ultimatestaff.alerts.xray.learning
  approvemessage:
    description: Approve message for autowatch
    aliases: [approve]
    permission: ultimatestaff.automod.approve
  denymessage:
    description: Blacklist message for autowatch
    aliases: [deny]
    permission: ultimatestaff.automod.deny


permissions:
  ultimatestaff.admin:
    description: Admin permission for all plugin features
    default: op
    children:
      ultimatestaff.staff: true
      ultimatestaff.admin.update: true
      ultimatestaff.admin.mining: true
      ultimatestaff.admin.mining.debug: true
      ultimatestaff.admin.restart: true
      ultimatestaff.admin.automod: true
      ultimatestaff.admin.restoredeathitems: true
      ultimatestaff.admin.chatfilter: true
      ultimatestaff.admin.punishdebug: true
      ultimatestaff.admin.discord: true
      ultimatestaff.automod.approve: true

  ultimatestaff.staff:
    description: Staff permission for core staff features
    default: op
    children:
      ultimatestaff.command: true
      ultimatestaff.staff.staffmode: true
      ultimatestaff.staff.invsee: true
      ultimatestaff.staff.endersee: true
      ultimatestaff.staff.teleport: true
      ultimatestaff.staff.miningalerts: true
      ultimatestaff.staff.punish: true
      ultimatestaff.staff.deathlocation: true
      ultimatestaff.staff.see_vanished: true
      ultimatestaff.staff.notify: true
      ultimatestaff.staff.chat: true
      ultimatestaff.staff.filter_alerts: true
      ultimatestaff.staff.clearchat: true
      ultimatestaff.staff.xray_commands: true

  ultimatestaff.admin.*:
    description: Gives access to all admin commands
    children:
      ultimatestaff.admin.updates: true
      ultimatestaff.admin.chat: true
      ultimatestaff.admin.reload: true
      ultimatestaff.admin.restoreitems: true
      ultimatestaff.admin.chatfilter: true
      ultimatestaff.admin.lag: true
      ultimatestaff.admin.automod: true
      ultimatestaff.admin.discord: true
      ultimatestaff.admin.punishdebug: true
      ultimatestaff.admin.debug: true
      ultimatestaff.admin.alerts.config: true
      ultimatestaff.admin.mining: true
      ultimatestaff.admin.mining.debug: true
      ultimatestaff.admin.restart: true
      ultimatestaff.admin.restoredeathitems: true

  ultimatestaff.staff.*:
    description: Gives access to all staff commands
    children:
      ultimatestaff.staff.chat: true
      ultimatestaff.staff.mode: true
      ultimatestaff.staff.vanish: true
      ultimatestaff.staff.spectator: true
      ultimatestaff.staff.freeze: true
      ultimatestaff.staff.invsee: true
      ultimatestaff.staff.endersee: true
      ultimatestaff.staff.teleport: true
      ultimatestaff.staff.restart: true
      ultimatestaff.staff.punish: true
      ultimatestaff.staff.clearchat: true
      ultimatestaff.staff.deathlocation: true
      ultimatestaff.staff.filter.bypass: true
      ultimatestaff.staff.filter.alerts: true
      ultimatestaff.staff.use: true
      ultimatestaff.staff.alerts.mining: true
      ultimatestaff.staff.staffmode: true
      ultimatestaff.staff.see_vanished: true
      ultimatestaff.staff.notify: true
      ultimatestaff.staff.xray_commands: true

  ultimatestaff.alerts.*:
    description: Gives access to all alerts
    children:
      ultimatestaff.alerts.mining: true
      ultimatestaff.alerts.xray: true
      ultimatestaff.alerts.xray.learning: true

  ultimatestaff.command:
    description: Permission to use the /ultimatestaff command
    default: op

  ultimatestaff.staff.staffmode:
    description: Permission to use staff mode
    default: op

  ultimatestaff.staff.invsee:
    description: Permission to view player inventories
    default: op

  ultimatestaff.staff.endersee:
    description: Permission to view player ender chests
    default: op

  ultimatestaff.staff.teleport:
    description: Permission to teleport to players
    default: op

  ultimatestaff.staff.alerts.mining:
    description: Allows receiving mining alerts
    default: op

  ultimatestaff.admin.alerts.config:
    description: Allows configuring mining alerts
    default: op

  ultimatestaff.staff.invsee.notify:
    description: Receive notifications when staff members modify player inventories
    default: op

  ultimatestaff.automod.bypass:
    description: Bypass the AutoMod system
    default: op

  ultimatestaff.automod.approve:
    description: Permission to approve messages in the AutoMod system
    default: op

  ultimatestaff.automod.deny:
    description: Permission to mark messages as inappropriate in the AutoMod system
    default: op