name: UltimateStaff
version: '1.0.3'
main: com.smokypeaks.Main
api-version: '1.21'
softdepends: [LuckPerms]
authors: [Hydrantz]  # Note the square brackets to make it a list
description: Ultimate staff management plugin
libraries:
  - com.google.code.gson:gson:2.10.1
commands:
  ultimatestaff:
    description: Main command for UltimateStaff plugin
    usage: /ultimatestaff <subcommand>
    aliases: [us, ustaff]
    permission: ultimatestaff.staff.use
  ultimatestaffupdate:
    description: Check for plugin updates
    usage: /ultimatestaffupdate
    permission: ultimatestaff.admin.updates
  staffmode:
    description: Toggle staff mode
    usage: /staffmode
    aliases: [ sm, staff ]
    permission: ultimatestaff.staff.mode
  endersee:
    description: View a player's enderchest
    usage: /endersee <player>
    aliases: [ echest, ec ]
    permission: ultimatestaff.staff.endersee
  stp:
    description: Staff teleport commands
    usage: /stp <player|random|back|pos> [args]
    aliases: [ stafftp ]
    permission: ultimatestaff.staff.teleport
  miningalerts:
    description: Toggle mining alerts
    usage: /miningalerts
    aliases: [ ma, minealert ]
    permission: ultimatestaff.staff.alerts.mining
  miningconfig:
    description: Configure mining alerts
    usage: /miningconfig <toggle|message|sound> <material> [args]
    permission: ultimatestaff.admin.alerts.config
  restart:
    description: Schedule a server restart
    usage: /restart <time> [reason]
    aliases: [ serverrestart, usrestart ]
    permission: ultimatestaff.admin.restart
  reloadpunishments:
    description: Reload punishment configurations
    permission: ultimatestaff.admin.reload
  miningdebug:
    description: Debug mining alert settings
    permission: ultimatestaff.admin.debug
  discordreload:
    description: Reload Discord integration
    usage: /discordreload
    permission: ultimatestaff.admin.discord

  clearchat:
    description: Clear the chat for all players or specific players
    usage: /clearchat [self|player <name>|all]
    aliases: [ cc ]
    permission: ultimatestaff.staff.clearchat

  punish:
    description: Open the punishment menu for a player
    usage: /punish <player>
    aliases: [ p, ban, mute, warn ]
    permission: ultimatestaff.staff.punish

  deathlocation:
    description: Check a player's last death location
    usage: /deathlocation [player]
    aliases: [ deathloc, dloc ]
    permission: ultimatestaff.staff.deathlocation

  restoredeathitems:
    description: Restore a player's items from their last death
    usage: /restoredeathitems <player>
    aliases: [ restoreitems, rditems ]
    permission: ultimatestaff.admin.restoreitems

  chatfilter:
    description: Manage the chat filter
    usage: /chatfilter <add|remove|list|toggle|replacement|reload> [args]
    aliases: [ cfilter, wordfilter ]
    permission: ultimatestaff.admin.chatfilter

      automod:
    description: Control the automatic moderation system
    usage: /automod <enable|disable|status|notify|clear|test|help> [args]
    aliases: [ am, amod ]
    permission: ultimatestaff.admin.automod

permissions:
  ultimatestaff.admin.*:
    description: Gives access to all admin commands
    children:
      ultimatestaff.admin.updates: true
      ultimatestaff.admin.chat: true
      ultimatestaff.admin.reload: true
      ultimatestaff.admin.restoreitems: true
      ultimatestaff.admin.chatfilter: true
      ultimatestaff.admin.lag: true
      ultimatestaff.admin.automod: true

  ultimatestaff.staff.*:
    description: Gives access to all staff commands
    children:
      ultimatestaff.staff.chat: true
      ultimatestaff.staff.mode: true
      ultimatestaff.staff.vanish: true
      ultimatestaff.staff.spectator: true
      ultimatestaff.staff.freeze: true
      ultimatestaff.staff.invsee: true
      ultimatestaff.staff.endersee: true
      ultimatestaff.staff.teleport: true
      ultimatestaff.staff.restart: true
      ultimatestaff.staff.punish: true
      ultimatestaff.staff.clearchat: true
      ultimatestaff.staff.deathlocation: true
      ultimatestaff.staff.filter.bypass: true
      ultimatestaff.staff.filter.alerts: true
      ultimatestaff.staff.use: true

  ultimatestaff.alerts.*:
    description: Gives access to all alerts
    children:
      ultimatestaff.alerts.mining: true

  ultimatestaff.admin.inventory.modify:
    description: Allows modification of player inventories
    default: op
    ultimatestaff.staff.inventory.view:
      description: Allows viewing player inventories
      default: false
    ultimatestaff.alerts.mining:
      description: Allows receiving mining alerts
      default: false
  ultimatestaff.staff.alerts.mining:
    description: Allows receiving mining alerts
    default: op
    ultimatestaff.admin.alerts.config:
      description: Allows configuring mining alerts
      default: op
  ultimatestaff.staff.invsee.notify:
    description: Receive notifications when staff members modify player inventories
    default: op
      ultimatestaff.automod.bypass:
    description: Bypass the AutoMod system
    default: op